### ISSUE TITLE
No results found, try again with a different query!

### ISSUE THREAD

**Issue by a59** [venthur/gscholar#13]
I just installed gscholar under OS X 10.12.3 using pip.

The script is installed in

`/usr/local/lib/python2.7/site-packages/gscholar/`

so I ran

`python /usr/local/lib/python2.7/site-packages/gscholar/gscholar.py -d "Albert Einstein"`

and got the following response

DEBUG:root:Assuming you want me to lookup the query: Albert Einstein
DEBUG:root:Query: Albert Einstein
No results found, try again with a different query!

does that mean something is broken?

**Comment by thundergolfer** [comment]
I'm also getting `[]` as a result to `gscholar.query` when I'm inputting paper titles that I know exist in Google Scholar's database.

**Comment by venthur** [comment]
I think google changed something with the cookies and I have to figure out what I need to send now in order to get a proper reply.
