### ISSUE TITLE
Package seem to be broken. Queries return nothing.

### ISSUE THREAD

**Issue by thundergolfer** [venthur/gscholar#14]
### Description 

I `pip install`ed this package hoping to use it to search *Google Scholar* by title, but even queries for famous author's and papers are returning `[]`. an empty list. Seeing as this is the core functionality of the package it's a pretty big problem.

#### Steps to reproduce

1. `pip install gscholar`
2. `python3`
3. `from gscholar import gscholar`
4. `gscholar.query("Albert Einstein")` **or** `gscholar.query("A Mathematical Theory of Communication")`

#### Expected Behaviour

A non-empty list of Einstein's papers, or having Claude E. Shannon's Information Theory paper returned. 

#### Actual Behaviour

returns `[]` in both cases. Seems to return `[]` for all queries.

**Comment by benlaken** [comment]
Same behaviour for me. Package currently seems unusable.

**Comment by mfe5003** [comment]
The package worked a while ago.
I am pretty sure that the issue is that the fake google id no longer is accepted.
from lines 54-56:
`# fake google id (looks like it is a 16 elements hex)`
`rand_str = str(random.random()).encode('utf8')`
`google_id = hashlib.md5(rand_str).hexdigest()[:16]`

**Comment by venthur** [comment]
Apparently they use different cookies now. Any help to generate a cookie google accepts is welcome!
