### ISSUE TITLE
version 1.6 is missing tar-ball on pypi

### ISSUE THREAD

**Issue by arunpersaud** [venthur/gscholar#19]
can you make the tar-ball available on pypi again? (openSUSE, for example, relies on these to build their packages)

**Comment by venthur** [comment]
Well, they should rather use the source from this github repository then and base their packages on that. I don't know what Suse's policy on package building is, but in Debian there is a strong preference to base the package on the actual repository, certainly not an artifact on pypi.

So I'd propose to `git clone` this repository and generate the `tar` yourself if you need it for package building.
